# Generated by Django 5.1.7 on 2025-03-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boletins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField()),
                ('nome_do_aluno', models.CharField(max_length=100)),
                ('nota1', models.FloatField()),
                ('nota2', models.FloatField()),
            ],
        ),
    ]
